// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAEfVaQFnE9DBmUaaGzsGo5Ffj4yqsbZU',
    appId: '1:1041395551734:web:61ac9d0351ac723c794bd7',
    messagingSenderId: '1041395551734',
    projectId: 'ccturismo-5ff7a',
    authDomain: 'ccturismo-5ff7a.firebaseapp.com',
    storageBucket: 'ccturismo-5ff7a.firebasestorage.app',
    measurementId: 'G-YP40YHCG6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvuH2_2xdxZTbIBuI03HUPmnTAcQuOzXU',
    appId: '1:1041395551734:android:ef4722c9030c4fda794bd7',
    messagingSenderId: '1041395551734',
    projectId: 'ccturismo-5ff7a',
    storageBucket: 'ccturismo-5ff7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjI1qKXRfWECe4plPQHwzv4ozAS99ngh4',
    appId: '1:1041395551734:ios:2b6345637b28ff4a794bd7',
    messagingSenderId: '1041395551734',
    projectId: 'ccturismo-5ff7a',
    storageBucket: 'ccturismo-5ff7a.firebasestorage.app',
    iosBundleId: 'com.example.projetotcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjI1qKXRfWECe4plPQHwzv4ozAS99ngh4',
    appId: '1:1041395551734:ios:2b6345637b28ff4a794bd7',
    messagingSenderId: '1041395551734',
    projectId: 'ccturismo-5ff7a',
    storageBucket: 'ccturismo-5ff7a.firebasestorage.app',
    iosBundleId: 'com.example.projetotcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAEfVaQFnE9DBmUaaGzsGo5Ffj4yqsbZU',
    appId: '1:1041395551734:web:c2709992d7b0e367794bd7',
    messagingSenderId: '1041395551734',
    projectId: 'ccturismo-5ff7a',
    authDomain: 'ccturismo-5ff7a.firebaseapp.com',
    storageBucket: 'ccturismo-5ff7a.firebasestorage.app',
    measurementId: 'G-CVH0F3R24L',
  );
}
